---
- hosts: all
  tasks:
  - shell: find /backup/ -type f | cut -d'/' -f3
    register: files_to_copy
  - fetch: src=/backup/{{item}} dest=backup/{{inventory_hostname}}/ flat=1
    with_items: files_to_copy.stdout_lines
